### PR TITLE
added transaction id info

### PR DESCRIPTION
**Pull request by flipchan**

### CODE REVIEW

**Comment by 59adc5ed-4a64-4984-bf6a-2b9117da6625** [comment]
Awesome add!

When I get home I'll run some quick tests against this and merge it if it all checks out.

**Comment by 59adc5ed-4a64-4984-bf6a-2b9117da6625** [comment]
@flipchan 

Ah actually quick fix, only things that should be in the constructor are used between calls. It looks like the txid should rather be a parameter to the ```def getTransactionInfo(self, params={}):``` call


for example:

post_params = {
    'txid' : theid,
   
}

**Comment by flipchan** [comment]
well yeah it works both ways, 
`
check = CryptoPayments(pkey.get("pubkey"), pkey.get("privkey"), ipn_url=False,txinfo=transaction.txn_id).getTransactionInfo()    
`

**Comment by 59adc5ed-4a64-4984-bf6a-2b9117da6625** [comment]
The point of this class is a reusable API object, I make the constructor more generic so when people need this in a larger framework they can just wrap it.

There's also a big security issue with keeping private/public keys in memory. If you're creating this constructor every time you want to make a call that means you're keeping the keys in memory, generally that's bad practice these should be injected at first run; and hence why the constructor was coded this way.

```python
check = CryptoPayments(pkey.get("pubkey"), pkey.get("privkey"), ipn_url=False,txinfo=transaction.txn_id).getTransactionInfo()
```

should be something along the lines of this:

```python
check = CryptoPayments(pkey.get("pubkey"), pkey.get("privkey"), ipn_url=False).getTransactionInfo(transaction.txn_id)
```

**Comment by flipchan** [comment]
NIce!
yeah 
```
check = CryptoPayments(pkey.get("pubkey"), pkey.get("privkey"), ipn_url=False).getTransactionInfo(transaction.txn_id)
```
looks like better and cleaner syntax

**Comment by 59adc5ed-4a64-4984-bf6a-2b9117da6625** [comment]
@flipchan 
If you can make it to reflect that I'll merge immediately, it's a good addition. I just want to keep the use flow the same.

**Comment by flipchan** [comment]
Changed it(call with txid as a argument getTransactionInfo(txidhere)), Merge it!

**Comment by 59adc5ed-4a64-4984-bf6a-2b9117da6625** [comment]
Man I'm sorry about the wait, here it goes.

**Comment by flipchan** [comment]
nice!

**Pull request merged**
